### ISSUE TITLE
run the proj

### ISSUE THREAD

**Issue by moh1122** [DashiDashCam/iOS-App#79]
Hello
Now that's a great proj
Shall i enable icloud capabilities in order to run it.

**Comment by LittleBoxOfSunshine** [comment]
This is our senior design app, so it lacks a lot of polish that prevents crashing. You will need to set up your own instance of the open source server code if you wish to run the project. There are some undocumented bugs related to file transfers dependent on the network settings / background mode if I recall correctly. In other words it works but isn't release ready. Feel free to do with it what you please.
